# Nomeando os componentes do Agente Coletor (agenteavro)
agenteavro.sources = ft
agenteavro.channels = cl
agenteavro.sinks = dt

# Configuração da Fonte (Source) com Interceptor de Filtragem
agenteavro.sources.ft.type = exec
agenteavro.sources.ft.command = tail -F /tmp/access_log
agenteavro.sources.ft.interceptors = e1
agenteavro.sources.ft.interceptors.e1.type = regex_filter
agenteavro.sources.ft.interceptors.e1.regex = 16.180.70.237
agenteavro.sources.ft.interceptors.e1.excludeEvents = false
agenteavro.sources.ft.channels = cl

# Configuração do Sink Avro (Emissor)
agenteavro.sinks.dt.type = avro
agenteavro.sinks.dt.hostname = localhost
agenteavro.sinks.dt.port = 44444
agenteavro.sinks.dt.channel = cl

# Canal em Memória do Agente Coletor
agenteavro.channels.cl.type = memory
agenteavro.channels.cl.capacity = 1000
agenteavro.channels.cl.transactionCapacity = 100

# -----------------------------------------------------------

# Nomeando os componentes do Agente Receptor (agentehdfs)
agentehdfs.sources = ft
agentehdfs.channels = cl
agentehdfs.sinks = dt

# Configuração da Fonte Avro (Receptor)
agentehdfs.sources.ft.type = avro
agentehdfs.sources.ft.bind = localhost
agentehdfs.sources.ft.port = 44444
agentehdfs.sources.ft.channels = cl

# Configuração do Sink HDFS (Arquivista)
agentehdfs.sinks.dt.type = hdfs
agentehdfs.sinks.dt.hdfs.path = /user/datalake/raw
agentehdfs.sinks.dt.hdfs.filePrefix = filter_log_web
agentehdfs.sinks.dt.hdfs.fileType = DataStream
agentehdfs.sinks.dt.hdfs.writeFormat = Text
agentehdfs.sinks.dt.hdfs.rollInterval = 30
agentehdfs.sinks.dt.hdfs.rollSize = 0
agentehdfs.sinks.dt.hdfs.rollCount = 10
agentehdfs.sinks.dt.channel = cl

# Canal em Memória do Agente Receptor
agentehdfs.channels.cl.type = memory
agentehdfs.channels.cl.capacity = 1000
agentehdfs.channels.cl.transactionCapacity = 100

